# suppress inspection "UnusedProperty" for whole file

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create
spring.datasource.driverClass = com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb?useSSL=false&&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.userName= root
spring.datasource.passWord= joban
spring.datasource.poolSize= 10
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#grpc.server.port=${PORT:0}
grpc.server.port=8084
server.port=${grpc.server.port}

spring.application.name=inventory-service

eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
eureka.instance.non-secure-port=${grpc.server.port}

springdoc.api-docs.path=/inventory-service/v3/api-docs
springdoc.swagger-ui.path=/inventory-service/swagger-ui


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# activate hidden actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# to populate info endpoint
management.info.env.enabled=true
info.app.name=inventory-service
info.app.description=Inventory-Service
info.app.version=1

# to enable shutdown endpoint in actuator
#management.endpoint.shutdown.enabled=true

# enable graceful shutdown from actuator endpoint
server.shutdown=graceful
# gracefull shutdown means all the ongoing request will completed and then the server will shutdown


# trace every request | in prod reduce sampling rate to 0.6
management.tracing.sampling.probability=1.0
