services:

  mongo-db:
    image: mongo
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: joban
      MONGO_INITDB_ROOT_PASSWORD: joban
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - microservicenetwork


  mysql:
    image: mysql
    container_name: mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: joban
      MYSQL_USER: joban
      MYSQL_PASSWORD: joban
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservicenetwork


  cart-service:
    image: acrcw/cart-service:kafka
    build:
      context: ./cart-service
    container_name: cart-service
    depends_on:
      - mongo-db
      - eureka-service
    environment:
      - GRPC_SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://joban:joban@mongo-db:27017/
      - SPRING_DATA_MONGODB_DATABASE=Carts
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=cart-service
    networks:
      - microservicenetwork


  inventory-service:
    image: acrcw/inventory-service:kafka
    build:
      context: ./inventory-service
    container_name: inventory-service
    depends_on:
      - mysql
      - eureka-service
    environment:
      - GRPC_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/inventorydb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=joban
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=inventory-service
    networks:
      - microservicenetwork


  notification-service:
    image: acrcw/notification-service:kafka
    build:
      context: ./notification-service
    container_name: notification-service
    depends_on:
      - eureka-service
    environment:
      - GRPC_SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=notification-service
    networks:
      - microservicenetwork


  order-service:
    image: acrcw/order-service:kafka
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      - mysql
      - eureka-service
    environment:
      - GRPC_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=joban
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=order-service
    networks:
      - microservicenetwork


  order-validation-service:
    image: acrcw/order-validation-service:kafka
    build:
      context: ./order-validation-service
    container_name: order-validation-service
    depends_on:
      - eureka-service
    environment:
      - GRPC_SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=order-validation-service
    networks:
      - microservicenetwork


  order-validation-retry-service:
    image: acrcw/order-validation-service-retry1:kafka
    build:
      context: ./order-validation-service-retry1
    container_name: order-validation-retry-service
    depends_on:
      - eureka-service
      - mongo-db
    environment:
      - GRPC_SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://joban:joban@mongo-db:27017/
      - SPRING_DATA_MONGODB_DATABASE=OrdersToValidate
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=order-validation-retry-service
    networks:
      - microservicenetwork


  product-service:
    image: acrcw/product-service:kafka
    build:
      context: ./product-service
    container_name: product-service
    depends_on:
      - eureka-service
      - mongo-db
    environment:
      - GRPC_SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://joban:joban@mongo-db:27017/
      - SPRING_DATA_MONGODB_DATABASE=Products
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=product-service
    networks:
      - microservicenetwork


  user-service:
    image: acrcw/user-service:kafka
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - eureka-service
      - mongo-db
    environment:
      - GRPC_SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=mongodb://joban:joban@mongo-db:27017/
      - SPRING_DATA_MONGODB_DATABASE=Users
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

      # 🔑 AWS MSK SERVERLESS
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=b-1.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094,b-2.otelprometheusintegra.6ngfgi.c3.kafka.ap-south-1.amazonaws.com:9094
      # - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      # - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
      # - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      # - SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
      # - AWS_REGION=ap-south-1

      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=user-service
    networks:
      - microservicenetwork


  eureka-service:
    image: acrcw/eureka-service:kafka
    build:
      context: ./discovery-server
    container_name: eureka-service
    environment:
      - SERVER_PORT=8761
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=eureka-service
    ports:
      - "8761:8761"
    networks:
      - microservicenetwork


  API-Gateway-service:
    image: acrcw/api-gateway:kafka
    build:
      context: ./api-gateway
    container_name: API-Gateway-service
    depends_on:
      - eureka-service
    environment:
      - GRPC_SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318
      - OTEL_SERVICE_NAME=API-Gateway-service
    ports:
      - "8080:8080"
    networks:
      - microservicenetwork


  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: opentelemetry-collector
    restart: unless-stopped
    volumes:
      - ./otel_config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
    networks:
      - microservicenetwork


networks:
  microservicenetwork:
    driver: bridge


volumes:
  mongodb_data_container:
  mysql-data:
